export const GET_RANDOM_PLANET_PENDING = 'GET_RANDOM_PLANET_PENDING';
export const GET_RANDOM_PLANET_DONE = 'GET_RANDOM_PLANET_DONE';
export const GET_RANDOM_PLANET_ERROR = 'GET_RANDOM_PLANET_ERROR';
